// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: unitdb.proto

package schema

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Unitdb_Stream_FullMethodName = "/unitdb.schema.Unitdb/Stream"
)

// UnitdbClient is the client API for Unitdb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Unitdb server interface
type UnitdbClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, Packet], error)
}

type unitdbClient struct {
	cc grpc.ClientConnInterface
}

func NewUnitdbClient(cc grpc.ClientConnInterface) UnitdbClient {
	return &unitdbClient{cc}
}

func (c *unitdbClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, Packet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Unitdb_ServiceDesc.Streams[0], Unitdb_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Packet, Packet]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Unitdb_StreamClient = grpc.BidiStreamingClient[Packet, Packet]

// UnitdbServer is the server API for Unitdb service.
// All implementations must embed UnimplementedUnitdbServer
// for forward compatibility.
//
// Unitdb server interface
type UnitdbServer interface {
	Stream(grpc.BidiStreamingServer[Packet, Packet]) error
	mustEmbedUnimplementedUnitdbServer()
}

// UnimplementedUnitdbServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnitdbServer struct{}

func (UnimplementedUnitdbServer) Stream(grpc.BidiStreamingServer[Packet, Packet]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedUnitdbServer) mustEmbedUnimplementedUnitdbServer() {}
func (UnimplementedUnitdbServer) testEmbeddedByValue()                {}

// UnsafeUnitdbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnitdbServer will
// result in compilation errors.
type UnsafeUnitdbServer interface {
	mustEmbedUnimplementedUnitdbServer()
}

func RegisterUnitdbServer(s grpc.ServiceRegistrar, srv UnitdbServer) {
	// If the following call panics, it indicates UnimplementedUnitdbServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Unitdb_ServiceDesc, srv)
}

func _Unitdb_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UnitdbServer).Stream(&grpc.GenericServerStream[Packet, Packet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Unitdb_StreamServer = grpc.BidiStreamingServer[Packet, Packet]

// Unitdb_ServiceDesc is the grpc.ServiceDesc for Unitdb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Unitdb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unitdb.schema.Unitdb",
	HandlerType: (*UnitdbServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Unitdb_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "unitdb.proto",
}
