// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: unitdb.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowControl int32

const (
	FlowControl_NONE        FlowControl = 0
	FlowControl_ACKNOWLEDGE FlowControl = 1
	FlowControl_NOTIFY      FlowControl = 2
	FlowControl_RECEIVE     FlowControl = 3
	FlowControl_RECEIPT     FlowControl = 4
	FlowControl_COMPLETE    FlowControl = 5
)

// Enum value maps for FlowControl.
var (
	FlowControl_name = map[int32]string{
		0: "NONE",
		1: "ACKNOWLEDGE",
		2: "NOTIFY",
		3: "RECEIVE",
		4: "RECEIPT",
		5: "COMPLETE",
	}
	FlowControl_value = map[string]int32{
		"NONE":        0,
		"ACKNOWLEDGE": 1,
		"NOTIFY":      2,
		"RECEIVE":     3,
		"RECEIPT":     4,
		"COMPLETE":    5,
	}
)

func (x FlowControl) Enum() *FlowControl {
	p := new(FlowControl)
	*p = x
	return p
}

func (x FlowControl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowControl) Descriptor() protoreflect.EnumDescriptor {
	return file_unitdb_proto_enumTypes[0].Descriptor()
}

func (FlowControl) Type() protoreflect.EnumType {
	return &file_unitdb_proto_enumTypes[0]
}

func (x FlowControl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowControl.Descriptor instead.
func (FlowControl) EnumDescriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_RERSERVED   MessageType = 0
	MessageType_CONNECT     MessageType = 1
	MessageType_PUBLISH     MessageType = 2
	MessageType_RELAY       MessageType = 3
	MessageType_SUBSCRIBE   MessageType = 4
	MessageType_UNSUBSCRIBE MessageType = 5
	MessageType_PINGREQ     MessageType = 6
	MessageType_DISCONNECT  MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "RERSERVED",
		1: "CONNECT",
		2: "PUBLISH",
		3: "RELAY",
		4: "SUBSCRIBE",
		5: "UNSUBSCRIBE",
		6: "PINGREQ",
		7: "DISCONNECT",
	}
	MessageType_value = map[string]int32{
		"RERSERVED":   0,
		"CONNECT":     1,
		"PUBLISH":     2,
		"RELAY":       3,
		"SUBSCRIBE":   4,
		"UNSUBSCRIBE": 5,
		"PINGREQ":     6,
		"DISCONNECT":  7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_unitdb_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_unitdb_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_unitdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_unitdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{1}
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FixedHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   MessageType            `protobuf:"varint,1,opt,name=MessageType,proto3,enum=unitdb.schema.MessageType" json:"MessageType,omitempty"`
	FlowControl   FlowControl            `protobuf:"varint,2,opt,name=FlowControl,proto3,enum=unitdb.schema.FlowControl" json:"FlowControl,omitempty"`
	MessageLength int32                  `protobuf:"varint,3,opt,name=MessageLength,proto3" json:"MessageLength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedHeader) Reset() {
	*x = FixedHeader{}
	mi := &file_unitdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedHeader) ProtoMessage() {}

func (x *FixedHeader) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedHeader.ProtoReflect.Descriptor instead.
func (*FixedHeader) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{2}
}

func (x *FixedHeader) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_RERSERVED
}

func (x *FixedHeader) GetFlowControl() FlowControl {
	if x != nil {
		return x.FlowControl
	}
	return FlowControl_NONE
}

func (x *FixedHeader) GetMessageLength() int32 {
	if x != nil {
		return x.MessageLength
	}
	return 0
}

// Connect represents a CONNECT Message type.
type Connect struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             int32                  `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	InsecureFlag        bool                   `protobuf:"varint,2,opt,name=InsecureFlag,proto3" json:"InsecureFlag,omitempty"`
	ClientID            string                 `protobuf:"bytes,3,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	KeepAlive           int32                  `protobuf:"varint,4,opt,name=KeepAlive,proto3" json:"KeepAlive,omitempty"`
	CleanSessFlag       bool                   `protobuf:"varint,5,opt,name=CleanSessFlag,proto3" json:"CleanSessFlag,omitempty"`
	SessKey             int32                  `protobuf:"varint,6,opt,name=SessKey,proto3" json:"SessKey,omitempty"`
	Username            string                 `protobuf:"bytes,7,opt,name=Username,proto3" json:"Username,omitempty"`
	Password            []byte                 `protobuf:"bytes,8,opt,name=Password,proto3" json:"Password,omitempty"`
	BatchDuration       int32                  `protobuf:"varint,9,opt,name=BatchDuration,proto3" json:"BatchDuration,omitempty"`
	BatchByteThreshold  int32                  `protobuf:"varint,10,opt,name=BatchByteThreshold,proto3" json:"BatchByteThreshold,omitempty"`
	BatchCountThreshold int32                  `protobuf:"varint,11,opt,name=BatchCountThreshold,proto3" json:"BatchCountThreshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_unitdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{3}
}

func (x *Connect) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Connect) GetInsecureFlag() bool {
	if x != nil {
		return x.InsecureFlag
	}
	return false
}

func (x *Connect) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Connect) GetKeepAlive() int32 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

func (x *Connect) GetCleanSessFlag() bool {
	if x != nil {
		return x.CleanSessFlag
	}
	return false
}

func (x *Connect) GetSessKey() int32 {
	if x != nil {
		return x.SessKey
	}
	return 0
}

func (x *Connect) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Connect) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *Connect) GetBatchDuration() int32 {
	if x != nil {
		return x.BatchDuration
	}
	return 0
}

func (x *Connect) GetBatchByteThreshold() int32 {
	if x != nil {
		return x.BatchByteThreshold
	}
	return 0
}

func (x *Connect) GetBatchCountThreshold() int32 {
	if x != nil {
		return x.BatchCountThreshold
	}
	return 0
}

// ConnectAcknowledge represents a CONNECT Acknowledge Message type.
// 0x00 connection accepted
// 0x01 refused: unacceptable proto version
// 0x02 refused: identifier rejected
// 0x03 refused: unacceptable identifier, access not allowed
// 0x04 refused server unavailiable
// 0x05 not authorized
// 0x06 bad request
type ConnectAcknowledge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    int32                  `protobuf:"varint,1,opt,name=ReturnCode,proto3" json:"ReturnCode,omitempty"`
	Epoch         int32                  `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	ConnID        int32                  `protobuf:"varint,3,opt,name=ConnID,proto3" json:"ConnID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAcknowledge) Reset() {
	*x = ConnectAcknowledge{}
	mi := &file_unitdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAcknowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAcknowledge) ProtoMessage() {}

func (x *ConnectAcknowledge) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAcknowledge.ProtoReflect.Descriptor instead.
func (*ConnectAcknowledge) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectAcknowledge) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *ConnectAcknowledge) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ConnectAcknowledge) GetConnID() int32 {
	if x != nil {
		return x.ConnID
	}
	return 0
}

// PingRequest is a keepalive
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_unitdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{5}
}

// Disconnect is to signal client want to cease communications with the server.
type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageID     int32                  `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_unitdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{6}
}

func (x *Disconnect) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

type PublishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Ttl           string                 `protobuf:"bytes,3,opt,name=Ttl,proto3" json:"Ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessage) Reset() {
	*x = PublishMessage{}
	mi := &file_unitdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessage) ProtoMessage() {}

func (x *PublishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessage.ProtoReflect.Descriptor instead.
func (*PublishMessage) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{7}
}

func (x *PublishMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishMessage) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

// Publish represents a PUBREQ Message type. It supports following delivery mode.
// 0 EXPRESS
// 1 RELIEABLE
// 2 BATCH
type Publish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageID     int32                  `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	DeliveryMode  int32                  `protobuf:"varint,2,opt,name=DeliveryMode,proto3" json:"DeliveryMode,omitempty"`
	Messages      []*PublishMessage      `protobuf:"bytes,3,rep,name=Messages,proto3" json:"Messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publish) Reset() {
	*x = Publish{}
	mi := &file_unitdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{8}
}

func (x *Publish) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *Publish) GetDeliveryMode() int32 {
	if x != nil {
		return x.DeliveryMode
	}
	return 0
}

func (x *Publish) GetMessages() []*PublishMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// RelayRequest is pairing the Topic and Last parameter together
type RelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Last          string                 `protobuf:"bytes,2,opt,name=Last,proto3" json:"Last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_unitdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{9}
}

func (x *RelayRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RelayRequest) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

// Relay tells the server which topics and last durations the client would like get data persisted on Servr. The Delivery Mode for relay is EXPRESS.
type Relay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageID     int32                  `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	RelayRequests []*RelayRequest        `protobuf:"bytes,2,rep,name=relayRequests,proto3" json:"relayRequests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relay) Reset() {
	*x = Relay{}
	mi := &file_unitdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relay) ProtoMessage() {}

func (x *Relay) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relay.ProtoReflect.Descriptor instead.
func (*Relay) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{10}
}

func (x *Relay) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *Relay) GetRelayRequests() []*RelayRequest {
	if x != nil {
		return x.RelayRequests
	}
	return nil
}

// Subscription is pairing the Delivery Mode and Topic together
// for the delivery mode's pairs in unsubscribe and subscribe.
// Delay in Millisecond to delay the messsage delivery if DeliveryMode is RELIEABLE or BATCH.
// 0 EXPRESS
// 1 RELIEABLE
// 2 BATCH
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryMode  int32                  `protobuf:"varint,1,opt,name=DeliveryMode,proto3" json:"DeliveryMode,omitempty"`
	Delay         int32                  `protobuf:"varint,2,opt,name=Delay,proto3" json:"Delay,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=Topic,proto3" json:"Topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_unitdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{11}
}

func (x *Subscription) GetDeliveryMode() int32 {
	if x != nil {
		return x.DeliveryMode
	}
	return 0
}

func (x *Subscription) GetDelay() int32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *Subscription) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// Subscribe tells the server which topics the client would like to subscribe to and choose a Delivery Mode.
type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageID     int32                  `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,2,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_unitdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{12}
}

func (x *Subscribe) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *Subscribe) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// Unsubscribe is the Message to send if you don't want to subscribe to a topic anymore.
type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageID     int32                  `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,2,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_unitdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{13}
}

func (x *Unsubscribe) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *Unsubscribe) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

// ControlMessage is a Flow Control Message.
type ControlMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageID int32                  `protobuf:"varint,1,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	// Optional Control Message bytes
	Message       []byte `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_unitdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_unitdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_unitdb_proto_rawDescGZIP(), []int{14}
}

func (x *ControlMessage) GetMessageID() int32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *ControlMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_unitdb_proto protoreflect.FileDescriptor

const file_unitdb_proto_rawDesc = "" +
	"\n" +
	"\funitdb.proto\x12\runitdb.schema\"\a\n" +
	"\x05Empty\"\x1c\n" +
	"\x06Packet\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xaf\x01\n" +
	"\vFixedHeader\x12<\n" +
	"\vMessageType\x18\x01 \x01(\x0e2\x1a.unitdb.schema.MessageTypeR\vMessageType\x12<\n" +
	"\vFlowControl\x18\x02 \x01(\x0e2\x1a.unitdb.schema.FlowControlR\vFlowControl\x12$\n" +
	"\rMessageLength\x18\x03 \x01(\x05R\rMessageLength\"\x81\x03\n" +
	"\aConnect\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\x05R\aVersion\x12\"\n" +
	"\fInsecureFlag\x18\x02 \x01(\bR\fInsecureFlag\x12\x1a\n" +
	"\bClientID\x18\x03 \x01(\tR\bClientID\x12\x1c\n" +
	"\tKeepAlive\x18\x04 \x01(\x05R\tKeepAlive\x12$\n" +
	"\rCleanSessFlag\x18\x05 \x01(\bR\rCleanSessFlag\x12\x18\n" +
	"\aSessKey\x18\x06 \x01(\x05R\aSessKey\x12\x1a\n" +
	"\bUsername\x18\a \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\b \x01(\fR\bPassword\x12$\n" +
	"\rBatchDuration\x18\t \x01(\x05R\rBatchDuration\x12.\n" +
	"\x12BatchByteThreshold\x18\n" +
	" \x01(\x05R\x12BatchByteThreshold\x120\n" +
	"\x13BatchCountThreshold\x18\v \x01(\x05R\x13BatchCountThreshold\"b\n" +
	"\x12ConnectAcknowledge\x12\x1e\n" +
	"\n" +
	"ReturnCode\x18\x01 \x01(\x05R\n" +
	"ReturnCode\x12\x14\n" +
	"\x05Epoch\x18\x02 \x01(\x05R\x05Epoch\x12\x16\n" +
	"\x06ConnID\x18\x03 \x01(\x05R\x06ConnID\"\r\n" +
	"\vPingRequest\"*\n" +
	"\n" +
	"Disconnect\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x05R\tMessageID\"R\n" +
	"\x0ePublishMessage\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\fR\aPayload\x12\x10\n" +
	"\x03Ttl\x18\x03 \x01(\tR\x03Ttl\"\x86\x01\n" +
	"\aPublish\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x05R\tMessageID\x12\"\n" +
	"\fDeliveryMode\x18\x02 \x01(\x05R\fDeliveryMode\x129\n" +
	"\bMessages\x18\x03 \x03(\v2\x1d.unitdb.schema.PublishMessageR\bMessages\"8\n" +
	"\fRelayRequest\x12\x14\n" +
	"\x05Topic\x18\x01 \x01(\tR\x05Topic\x12\x12\n" +
	"\x04Last\x18\x02 \x01(\tR\x04Last\"h\n" +
	"\x05Relay\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x05R\tMessageID\x12A\n" +
	"\rrelayRequests\x18\x02 \x03(\v2\x1b.unitdb.schema.RelayRequestR\rrelayRequests\"^\n" +
	"\fSubscription\x12\"\n" +
	"\fDeliveryMode\x18\x01 \x01(\x05R\fDeliveryMode\x12\x14\n" +
	"\x05Delay\x18\x02 \x01(\x05R\x05Delay\x12\x14\n" +
	"\x05Topic\x18\x03 \x01(\tR\x05Topic\"l\n" +
	"\tSubscribe\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x05R\tMessageID\x12A\n" +
	"\rSubscriptions\x18\x02 \x03(\v2\x1b.unitdb.schema.SubscriptionR\rSubscriptions\"n\n" +
	"\vUnsubscribe\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x05R\tMessageID\x12A\n" +
	"\rSubscriptions\x18\x02 \x03(\v2\x1b.unitdb.schema.SubscriptionR\rSubscriptions\"H\n" +
	"\x0eControlMessage\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x05R\tMessageID\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\fR\aMessage*\\\n" +
	"\vFlowControl\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vACKNOWLEDGE\x10\x01\x12\n" +
	"\n" +
	"\x06NOTIFY\x10\x02\x12\v\n" +
	"\aRECEIVE\x10\x03\x12\v\n" +
	"\aRECEIPT\x10\x04\x12\f\n" +
	"\bCOMPLETE\x10\x05*~\n" +
	"\vMessageType\x12\r\n" +
	"\tRERSERVED\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\v\n" +
	"\aPUBLISH\x10\x02\x12\t\n" +
	"\x05RELAY\x10\x03\x12\r\n" +
	"\tSUBSCRIBE\x10\x04\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x05\x12\v\n" +
	"\aPINGREQ\x10\x06\x12\x0e\n" +
	"\n" +
	"DISCONNECT\x10\a2D\n" +
	"\x06Unitdb\x12:\n" +
	"\x06Stream\x12\x15.unitdb.schema.Packet\x1a\x15.unitdb.schema.Packet(\x010\x01B\n" +
	"Z\b.;schemab\x06proto3"

var (
	file_unitdb_proto_rawDescOnce sync.Once
	file_unitdb_proto_rawDescData []byte
)

func file_unitdb_proto_rawDescGZIP() []byte {
	file_unitdb_proto_rawDescOnce.Do(func() {
		file_unitdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unitdb_proto_rawDesc), len(file_unitdb_proto_rawDesc)))
	})
	return file_unitdb_proto_rawDescData
}

var file_unitdb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_unitdb_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_unitdb_proto_goTypes = []any{
	(FlowControl)(0),           // 0: unitdb.schema.FlowControl
	(MessageType)(0),           // 1: unitdb.schema.MessageType
	(*Empty)(nil),              // 2: unitdb.schema.Empty
	(*Packet)(nil),             // 3: unitdb.schema.Packet
	(*FixedHeader)(nil),        // 4: unitdb.schema.FixedHeader
	(*Connect)(nil),            // 5: unitdb.schema.Connect
	(*ConnectAcknowledge)(nil), // 6: unitdb.schema.ConnectAcknowledge
	(*PingRequest)(nil),        // 7: unitdb.schema.PingRequest
	(*Disconnect)(nil),         // 8: unitdb.schema.Disconnect
	(*PublishMessage)(nil),     // 9: unitdb.schema.PublishMessage
	(*Publish)(nil),            // 10: unitdb.schema.Publish
	(*RelayRequest)(nil),       // 11: unitdb.schema.RelayRequest
	(*Relay)(nil),              // 12: unitdb.schema.Relay
	(*Subscription)(nil),       // 13: unitdb.schema.Subscription
	(*Subscribe)(nil),          // 14: unitdb.schema.Subscribe
	(*Unsubscribe)(nil),        // 15: unitdb.schema.Unsubscribe
	(*ControlMessage)(nil),     // 16: unitdb.schema.ControlMessage
}
var file_unitdb_proto_depIdxs = []int32{
	1,  // 0: unitdb.schema.FixedHeader.MessageType:type_name -> unitdb.schema.MessageType
	0,  // 1: unitdb.schema.FixedHeader.FlowControl:type_name -> unitdb.schema.FlowControl
	9,  // 2: unitdb.schema.Publish.Messages:type_name -> unitdb.schema.PublishMessage
	11, // 3: unitdb.schema.Relay.relayRequests:type_name -> unitdb.schema.RelayRequest
	13, // 4: unitdb.schema.Subscribe.Subscriptions:type_name -> unitdb.schema.Subscription
	13, // 5: unitdb.schema.Unsubscribe.Subscriptions:type_name -> unitdb.schema.Subscription
	3,  // 6: unitdb.schema.Unitdb.Stream:input_type -> unitdb.schema.Packet
	3,  // 7: unitdb.schema.Unitdb.Stream:output_type -> unitdb.schema.Packet
	7,  // [7:8] is the sub-list for method output_type
	6,  // [6:7] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_unitdb_proto_init() }
func file_unitdb_proto_init() {
	if File_unitdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unitdb_proto_rawDesc), len(file_unitdb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unitdb_proto_goTypes,
		DependencyIndexes: file_unitdb_proto_depIdxs,
		EnumInfos:         file_unitdb_proto_enumTypes,
		MessageInfos:      file_unitdb_proto_msgTypes,
	}.Build()
	File_unitdb_proto = out.File
	file_unitdb_proto_goTypes = nil
	file_unitdb_proto_depIdxs = nil
}
